# Generated by Django 5.2.10 on 2026-01-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=100)),
                ("student_email", models.EmailField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
            ],
        ),
    ]
